In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("data.csv")
df.head(10)

C:\Users\Connor\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (0,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Id,Title,Company,Date,Location,Area,Classification,SubClassification,Requirement,FullDescription,LowestSalary,HighestSalary,JobType
0,37404348,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Sydney,North West & Hills District,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,NaN,0,30,NaN
1,37404337,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Richmond & Hawkesbury,NaN,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,NaN,0,30,NaN
2,37404356,RETAIL SALES SUPERSTARS and STYLISTS Wanted - ...,LB Creative Pty Ltd,2018-10-07T00:00:00.000Z,Brisbane,CBD & Inner Suburbs,Retail & Consumer Products,Retail Assistants,BRAND NEW FLAGSHIP STORE OPENING - SUNSHINE PLAZA,NaN,0,30,NaN
3,37404330,Team member - Belrose,Anaconda Group Pty Ltd,2018-10-07T00:00:00.000Z,Gosford & Central Coast,NaN,Retail & Consumer Products,Retail Assistants,Bring it on - do you love the great outdoors a...,NaN,0,30,NaN
4,37404308,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Ryde & Macquarie Park,Call Centre & Customer Service,Sales - Inbound,"We are seeking highly articulate, enthusiastic...",NaN,0,30,NaN
5,37404307,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Ryde & Macquarie Park,Call Centre & Customer Service,Customer Service - Call Centre,"We are seeking highly articulate, enthusiastic...",NaN,0,30,NaN
6,37404355,Casual Café All-rounder in Semaphore,Jora Local,2018-10-07T00:00:00.000Z,Adelaide,NaN,Hospitality & Tourism,Waiting Staff,A cafe/restaurant in Semaphore is seeking a ca...,NaN,0,30,NaN
7,37404350,Casual Café All-rounder in Woolloongabba,Jora Local,2018-10-07T00:00:00.000Z,Brisbane,CBD & Inner Suburbs,Hospitality & Tourism,Waiting Staff,A cafe in Woolloongabba is seeking a casual Ca...,NaN,0,30,NaN
8,37404301,Telemarketer,Reventon Investments,2018-10-07T00:00:00.000Z,Melbourne,CBD & Inner Suburbs,Call Centre & Customer Service,Sales - Outbound,Market leading investment & financial services...,NaN,0,30,NaN
9,37404286,Casual Dish Hand in Brighton,Jora Local,2018-10-07T00:00:00.000Z,Melbourne,Bayside & South Eastern Suburbs,Hospitality & Tourism,Kitchen & Sandwich Hands,A restaurant in Brighton is seeking a casual D...,NaN,0,30,NaN

In [3]:
print(df.shape)
print(df.dtypes)

(318477, 13)
Id                   object
Title                object
Company              object
Date                 object
Location             object
Area                 object
Classification       object
SubClassification    object
Requirement          object
FullDescription      object
LowestSalary          int64
HighestSalary         int64
JobType              object
dtype: object

In [9]:
df.duplicated().sum()

0

In [5]:
df['Date']= pd.to_datetime(df['Date'])

In [6]:
print(df.dtypes)

Id                                object
Title                             object
Company                           object
Date                 datetime64[ns, UTC]
Location                          object
Area                              object
Classification                    object
SubClassification                 object
Requirement                       object
FullDescription                   object
LowestSalary                       int64
HighestSalary                      int64
JobType                           object
dtype: object

In [7]:
df.isnull().sum()

Id                        0
Title                     0
Company               12004
Date                      0
Location             121248
Area                 195819
Classification       121248
SubClassification    121248
Requirement               7
FullDescription       16175
LowestSalary              0
HighestSalary             0
JobType               16098
dtype: int64

In [20]:
df.groupby('Location').count()['Id'].sort_values(ascending=False)

Location
Sydney                                  60765
Melbourne                               46690
Brisbane                                21466
Perth                                   13198
Adelaide                                 6653
ACT                                      6250
Newcastle, Maitland & Hunter             3958
Gold Coast                               3588
South West Coast VIC                     1790
Mackay & Coalfields                      1701
Port Hedland, Karratha & Pilbara         1667
Wollongong, Illawarra & South Coast      1657
Sunshine Coast                           1554
Cairns & Far North                       1509
Northern QLD                             1493
Gosford & Central Coast                  1343
Toowoomba & Darling Downs                1310
Darwin                                   1266
Hobart                                   1051
Blue Mountains & Central West             942
Kalgoorlie, Goldfields & Esperance        870
Lismore & Far North Coast                 817
Bendigo, Goldfields & Macedon Ranges      808
Wagga Wagga & Riverina                    802
Mornington Peninsula & Bass Coast         739
Rockhampton & Capricorn Coast             728
Gladstone & Central QLD                   712
Dubbo & Central NSW                       642
Bunbury & South West                      635
Tamworth & North West NSW                 610
                                        ...
Port Macquarie & Mid North Coast          469
Southern Highlands & Tablelands           465
Coffs Harbour & North Coast               440
Albury Area                               416
Bundaberg & Wide Bay Burnett              409
Launceston & North East                   388
Bairnsdale & Gippsland                    378
Geraldton, Gascoyne & Midwest             341
Mildura & Murray                          307
Alice Springs & Central Australia         301
Hervey Bay & Fraser Coast                 285
Broome & Kimberley                        283
Devonport & North West                    256
Mandurah & Peel                           250
Horsham & Grampians                       209
Whyalla & Eyre Peninsula                  201
Far West & North Central NSW              197
Adelaide Hills & Barossa                  193
Katherine & Northern Australia            187
Mt Gambier & Limestone Coast              168
Northam & Wheatbelt                       160
Albany & Great Southern                   150
Riverland & Murray Mallee                 149
Richmond & Hawkesbury                     140
Coober Pedy & Outback SA                  112
Yorke Peninsula & Clare Valley             96
Tumut, Snowy & Monaro                      86
Somerset & Lockyer                         65
Fleurieu Peninsula & Kangaroo Island       64
Central & South East TAS                   57
Name: Id, Length: 65, dtype: int64

In [16]:
df.groupby('Location').mean()

                                      LowestSalary  HighestSalary
Location
ACT                                      86.174400     198.718240
Adelaide                                 57.991883      97.021494
Adelaide Hills & Barossa                 41.191710      68.948187
Albany & Great Southern                  56.600000     101.233333
Albury Area                              51.201923      75.543269
Alice Springs & Central Australia        64.186047     113.647841
Bairnsdale & Gippsland                   55.740741     105.328042
Ballarat & Central Highlands             53.067993      84.243781
Bendigo, Goldfields & Macedon Ranges     49.504950      70.402228
Blue Mountains & Central West            60.764331     108.487261
Brisbane                                 65.875804     121.621588
Broome & Kimberley                       66.431095     117.628975
Bunbury & South West                     50.866142      79.795276
Bundaberg & Wide Bay Burnett             61.149144     127.176039
Cairns & Far North                       54.440027      94.074884
Central & South East TAS                 51.754386      68.245614
Coffs Harbour & North Coast              54.318182     101.870455
Coober Pedy & Outback SA                 73.303571     107.125000
Darwin                                   68.467615     120.466035
Devonport & North West                   53.007812      87.750000
Dubbo & Central NSW                      66.915888     116.037383
Far West & North Central NSW             69.289340     110.888325
Fleurieu Peninsula & Kangaroo Island     42.968750      58.125000
Geraldton, Gascoyne & Midwest            73.489736     128.756598
Gladstone & Central QLD                  66.502809     104.528090
Gold Coast                               49.721293      82.994426
Gosford & Central Coast                  54.296351      88.876396
Hervey Bay & Fraser Coast                53.263158      99.575439
Hobart                                   55.480495      94.739296
Horsham & Grampians                      56.937799      91.698565
...                                            ...            ...
Mandurah & Peel                          56.320000      90.140000
Melbourne                                64.252302     113.982716
Mildura & Murray                         60.586319     118.872964
Mornington Peninsula & Bass Coast        43.951286      73.446549
Mt Gambier & Limestone Coast             55.178571     104.601190
Newcastle, Maitland & Hunter             59.044972     102.482062
Northam & Wheatbelt                      50.500000      77.362500
Northern QLD                             59.792364     113.129940
Perth                                    66.969238     117.191090
Port Hedland, Karratha & Pilbara         77.522496     121.421716
Port Macquarie & Mid North Coast         71.812367     149.605544
Richmond & Hawkesbury                    49.000000      77.842857
Riverland & Murray Mallee                48.926174      64.697987
Rockhampton & Capricorn Coast            64.972527     114.673077
Shepparton & Goulburn Valley             51.547421      85.850250
Somerset & Lockyer                       55.538462      97.353846
South West Coast VIC                     50.726257      79.979888
Southern Highlands & Tablelands          50.215054      79.918280
Sunshine Coast                           49.864865      86.640283
Sydney                                   71.882004     134.751041
Tamworth & North West NSW                61.278689     110.108197
Toowoomba & Darling Downs                51.076336      83.141221
Tumut, Snowy & Monaro                    67.558140     133.081395
Wagga Wagga & Riverina                   54.501247      87.087282
West Gippsland & Latrobe Valley          57.013889      93.586806
Western QLD                              69.357977     134.128405
Whyalla & Eyre Peninsula                 53.980100      86.000000
Wollongong, Illawarra & South Coast      55.829813      90.895594
Yarra Valley & High Country              44.168337      68.945892
Yorke Peninsula & Clare Valley           44.895833      77.791667

[65 rows x 2 columns]